# render.yaml (NİHAİ VE DOĞRU VERSİYON)

services:
  # Servis 1: Redis Veritabanı
  - type: redis
    name: redis-db
    plan: free
    ipAllowList: []

  # Servis 2: Web Servisi ve Worker
  - type: web
    name: app-and-worker
    env: python
    plan: free
    # EKSİK OLAN SATIRI BURAYA EKLİYORUZ:
    # Bu komut, Render'a requirements.txt dosyasındaki tüm paketleri kurmasını söyler.
    buildCommand: "pip install -r requirements.txt"
    
    # Başlangıç komutumuz zaten doğruydu:
    startCommand: "python -m honcho start"
    
    healthCheckPath: /_stcore/health
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-db
          property: connectionString
      # Diğer API anahtarlarınızı Render arayüzündeki "Environment" sekmesinden
      # eklemeyi unutmayın.

  # Servis 3: Streamlit Uygulaması
  - type: web
    name: streamlit-app
    env: python
    buildCommand: "ls -la && poetry install"
    startCommand: "streamlit run streamlit_app.py --server.port $PORT --server.enableCORS=false"