# render.yaml (NİHAİ VE DOĞRU VERSİYON)

services:
  # Servis 1: Redis Veritabanı
  - type: redis
    name: redis-db
    plan: free
    ipAllowList: []

  # Servis 2: Web Servisi ve Worker
  - type: web
    name: app-and-worker
    env: python
    plan: free
    # EKSİK OLAN SATIRI BURAYA EKLİYORUZ:
    # Bu komut, Render'a requirements.txt dosyasındaki tüm paketleri kurmasını söyler.
    buildCommand: "pip install -r requirements.txt"
    
    # Başlangıç komutumuz zaten doğruydu:
    startCommand: "python -m honcho start"
    
    healthCheckPath: /_stcore/health
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-db
          property: connectionString
      - key: RENDER_EXTERNAL_URL
        value: "https://app-and-worker.onrender.com"

  # Servis 3: Streamlit Uygulaması
  - type: web
    name: streamlit-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run streamlit_app.py --server.port $PORT --server.address 0.0.0.0 --server.enableCORS=false"
    healthCheckPath: /_stcore/health
    envVars:
      - key: RENDER_EXTERNAL_URL
        value: "https://streamlit-app.onrender.com"

  # Servis 4: Cron Job - Otomatik Sync
  - type: cron
    name: auto-sync-scheduler
    env: python
    buildCommand: "pip install -r requirements.txt"
    schedule: "0 */2 * * *"  # Her 2 saatte bir (120 dakika)
    startCommand: "timeout 15m python cron_scheduler.py"  # 15 dakika timeout (25'ten düşürüldü)
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-db
          property: connectionString
      - key: APP_URL
        value: "https://app-and-worker.onrender.com"
      - key: SYNC_BATCH_SIZE
        value: "5"  # 10'dan 5'e düşürüldü
      - key: SYNC_MAX_WORKERS
        value: "2"  # 3'ten 2'ye düşürüldü

  # Servis 5: Keep-Alive Service - Ana Uygulama
  - type: cron
    name: keep-alive-main
    env: python
    buildCommand: "pip install requests"
    schedule: "*/5 * * * *"  # Her 5 dakikada bir
    startCommand: "python -c 'import requests; import time; requests.get(\"https://app-and-worker.onrender.com/_stcore/health\", timeout=30); time.sleep(2); requests.get(\"https://streamlit-app.onrender.com/_stcore/health\", timeout=30); print(\"Keep-alive ping sent\")'"

  # Servis 6: Keep-Alive Service - Yedek
  - type: cron
    name: keep-alive-backup
    env: python
    buildCommand: "pip install requests"
    schedule: "2-57/5 * * * *"  # Her 5 dakikada bir (2 dakika offset ile)
    startCommand: "python -c 'import requests; requests.get(\"https://app-and-worker.onrender.com\", timeout=20); print(\"Backup ping sent\")'"