# render.yaml

services:
  # Servis 1: Redis Veritabanı (Değişiklik yok)
  - type: redis
    name: redis-db
    plan: free
    ipAllowList: []

  # Servis 2: Web Servisi ve Worker
  - type: web
    name: app-and-worker
    env: python
    plan: free
    # Başlangıç komutunu Python modülü olarak çalışacak şekilde güncelledik.
    startCommand: python -m honcho start
    healthCheckPath: /_stcore/health
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-db
          property: connectionString
      # ÖNEMLİ: Diğer API anahtarlarınızı (SHOPIFY_STORE, SHOPIFY_TOKEN, SENTOS_API_URL vb.)
      # Render arayüzündeki "Environment" sekmesinden eklemeyi unutmayın.