# render.yaml (2'si 1 arada versiyon)

services:
  # Servis 1: Redis Veritabanı (Değişiklik yok)
  - type: redis
    name: redis-db
    plan: free
    ipAllowList: []

  # Servis 2: Web Servisi (Artık Worker'ı da çalıştıracak)
  - type: web
    name: app-and-worker # İsim daha açıklayıcı oldu
    env: python
    plan: free
    # Başlangıç komutu artık honcho'yu çağırıyor.
    # honcho, Procfile içindeki 'web' ve 'worker' satırlarını aynı anda başlatacak.
    startCommand: honcho start
    healthCheckPath: /_stcore/health
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-db
          property: connectionString
      # Diğer ortam değişkenlerin Render arayüzünden eklenecek.